name:                aeson-generic-ts
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/smaccoun/aeson-generic-ts#readme
license:             BSD3
author:              Steven MacCoun
maintainer:          theraccoun@gmail.com
copyright:           2018 Steven MacCoun
category:            Web
extra-source-files:
- README.md


dependencies:
  - base >= 4.7 && < 5
  - text
  - aeson
  - exceptions
  - template-haskell
  - th-reify-many
  - th-abstraction

default-extensions:
- ConstraintKinds
- DataKinds
- DeriveGeneric
- FlexibleContexts
- FlexibleInstances
- KindSignatures
- MultiParamTypeClasses
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TypeFamilies
- UndecidableInstances
- DeriveAnyClass

library:
  source-dirs: src

tests:
  aeson-generic-ts-test:
    main: Spec.hs
    source-dirs:
      - test
      - src
      - data
    dependencies:
      - hspec
      - hspec-discover
      - markdown-unlit
    ghc-options: [-pgmL markdown-unlit]

  doctest:
    main: DocTest.hs
    source-dirs: .
    dependencies:
      - doctest
      - Glob

